export default {
    products : [
        {
            _id: '1',
            name: 'Hiskywin Full Zip Running Shirts',
            category: 'Shirts',
            image: './img/product-1.jpg',
            price: 59,
            brand: 'hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'product2',
            category: 'cat2',
            image: './img/product-2.jpg',
            price: 69,
            brand: 'brand2',
            rating: 3.5,
            numReviews: 20,
            countInStock: 16,
        },
        {
            _id: '3',
            name: 'product3',
            category: 'cat3',
            image: './img/product-3.jpg',
            price: 99,
            brand: 'brand3',
            rating: 2.5,
            numReviews: 14,
            countInStock: 4,
        },
        {
            _id: '4',
            name: 'product4',
            category: 'cat4',
            image: './img/product-4.jpg',
            price: 49,
            brand: 'brand4',
            rating: 3.5,
            numReviews: 12,
            countInStock: 9,
        },
        {
            _id: '5',
            name: 'product5',
            category: 'cat5',
            image: './img/product-5.jpg',
            price: 79,
            brand: 'brand5',
            rating: 3.5,
            numReviews: 17,
            countInStock: 16,
        },
        {
            _id: '6',
            name: 'product6',
            category: 'cat6',
            image: './img/product-6.jpg',
            price: 59,
            brand: 'brand6',
            rating: 1.5,
            numReviews: 11,
            countInStock: 32,
        },
        {
            _id: '7',
            name: 'product7',
            category: 'cat7',
            image: './img/product-7.jpg',
            price: 89,
            brand: 'brand7',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
       
    ],
}